server:
  port: 9093

actor:
  port: 8083

jwt:
  secret: xK8vN2pQ5wR7tY9uI3oP6aS8dF1gH4jK7lZ0xC3vB5nM2qW8eR4tY6uI9oP0aS3dF6gH9jK2lZ5xC8vB1nM4qW7e
  expiration: 3600000

# Configuration des services externes
user:
  service:
    url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres
    username: postgres.yldotyunksweuovyknzg
    password: Cypay.Cytech
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
